environment:
  discordWebhookUrl: REPLACE
  espnS2: REPLACE
  extraTrophies: true
  leagueId: REPLACE
  leagueYear: 2022
  randomPhrase: false
  swid: REPLACE
  test: false
  topHalfScoring: true
#   faab: REPLACE
#   users: REPLACE
#   emotes: REPLACE

# AWS CRON triggers are in UTC timezone only.
# UTC offsets Eastern Timezone (ET) by:
#   - 4 hours for EDT (spring & summer)
#   - 5 hours for EST (fall & winter)

# DELAY-AGNOSTIC
sundayScore:
  function: get_scoreboard_short
  events:
  - schedule: cron(0 0 20 ? * SUN *) # SUNDAY at 400PM EDT, or 2000 UTC
  - schedule: cron(0 0 0 ? * MON *) # SUNDAY at 800PM EDT, or MONDAY at 0000AM UTC
headsUpReport:
  function: get_heads_up
  events:
  - schedule: cron(0 30 20 ? * WED *) # WEDNESDAY at 430PM EDT, or 2030 UTC
matchups:
  function: get_matchups
  events:
  - schedule: cron(0 30 22 ? * WED *) # THURSDAY at 630PM EDT, or 2230 UTC
inactives:
  function: get_inactives
  events:
  - schedule: cron(0 0 0 ? * SUN *) # SATURDAY at 800PM EDT, or SUNDAY at 0000AM UTC

# NOT DELAYED
fridayAndMondayScore:
  function: get_scoreboard_short
  events:
  - schedule: cron(0 30 11 ? * FRI,MON *) # FRIDAY & MONDAY at 730AM EDT, or 1130 UTC
closeScores:
  function: get_close_scores
  events:
  - schedule: cron(0 30 22 ? * SUN,MON *) # SUNDAY & MONDAY at 630PM EDT, or 2230 UTC
finalScores:
  function: get_final
  events:
  - schedule: cron(0 30 11 ? * TUES *) # TUESDAY at 730AM EDT, or 1130 UTC
standings:
  function: get_standings
  events:
  - schedule: cron(0 30 22 ? * TUES *) # TUESDAY at 630PM EDT, or 2230 UTC
powerRankings:
  function: get_power_rankings
  events:
  - schedule: cron(0 30 22 ? * TUES *) # TUESDAY at 630PM EDT, or 2230 UTC
waiver:
  function: get_waiver_report
  events:
  - schedule: cron(0 00 12 ? * WED *) # WEDNESDAY at 800AM EDT, or 1200 UTC

# # DELAYED
# # Uncomment the following configs (and comment out the NOT DELAYED configs) in case
# # a delay causes games to be played on Tuesday (instead of the usual Thursday-Sunday
# # Monday slate).
# fridayAndMondayScore:
#   function: get_scoreboard_short
#   events:
#   - schedule: cron(0 30 11 ? * FRI,MON,TUES *) # FRIDAY, MONDAY, & TUESDAY at 730AM EDT, or 1130 UTC
# closeScores:
#   function: get_close_scores
#   events:
#   - schedule: cron(0 30 22 ? * SUN,MON,TUES *) # SUNDAY, MONDAY, & TUESDAY at 630PM EDT, or 2230 UTC
# finalScores:
#   function: get_final
#   events:
#   - schedule: cron(0 30 11 ? * WED *) # WEDNESDAY at 730AM EDT, or 1130 UTC
# standings:
#   function: get_standings
#   events:
#   - schedule: cron(0 30 22 ? * WED *) # WEDNESDAY at 630PM EDT, or 2230 UTC
# powerRankings:
#   function: get_power_rankings
#   events:
#   - schedule: cron(0 30 22 ? * WED *) # WEDNESDAY at 630PM EDT, or 2230 UTC
# waiver:
#   function: get_waiver_report
#   events:
#   - schedule: cron(0 00 12 ? * THURS *) # THURSDAY at 800AM EDT, or 1200 UTC
